### ISSUE TITLE
App concept?

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_anadanielkiewicz#1]
Hey @anadanielkiewicz lets keep track of your app concept here.

```
Final project topic (proposition): Beauty salon website.
Student: Anna Danielkiewicz

Beauty salon website.
It will be the site of a real make-up artist who has FB and a blog but no website. 
The logo will be used - thus the choice of page colors, a large number of professional photos and videos.

Links to the existing page on Facebook and the blog will be created.

Bookmarks: about us, offered beauty treatments, Q&A, gallery of performed works, certificates, contact.

I will focus here especially on the graphic page, but also on the page dynamics - that is, 
that the page would not be so static, but that the photos would move, transitions below, etc.
I would like to include the most frequently asked questions and answers in Q&A. 
If the customer does not find an answer, they can fill out the contact form, 
the content of which will be sent to the email of the owner of the page.
Contact + location in relation to the point on the map and google maps.

Ideas:
- Schedule - a hard matter, I haven't come up with a solution yet and I don't know if I can adapt it to my needs.
- Comments from Facebook attached to the page.
- Phone icon - the ability to call from a phone by clicking.
- Email icon - with the option of sending an email.
- ...

Important aspects I will have to face:
- website and data security,
- privacy policy,
- proper display of the page on every device,
- appropriate attachment of photos so that they do not slow down the movement of the website,
- ...

I would like to stay with it. I was wondering what I can do, which might be useful for me at work, 
but I don't know how JS is used in large companies. That's why I focused on creating pages, 
where I can also learn a lot and can someday use my own business. 
I also count on your support, ideas and maybe introducing me to the implementation of the site.
```

**Comment by BTBTravis** [comment]
Hey @anadanielkiewicz love the idea! Since your project sounds like a multi-page site perhaps we could utilize a static site generator to create all the HTML files for us. Then we could sprinkle in some Javascript in here and there for things like images sliders, accordions, and the contact form.

**Comment by BTBTravis** [comment]
Since you are interested in building a site may I ask you to building a site map with each page you want and it's approx content.

Here is a tool to do just that https://octopus.do/

And please save and share the octopus url here. 😀🐙

**Comment by anadanielkiewicz** [comment]
> 
> 
> Since you are interested in building a site may I ask you to building a site map with each page you want and it's approx content.
> 
> Here is a tool to do just that https://octopus.do/
> 
> And please save and share the octopus url here. 😀🐙

https://octopus.do/k4t06brxa7g

**Comment by BTBTravis** [comment]
Good work with the sitemap! You have quite a site you want to build. 👍 
Since your main focus is getting this bigger site up and running I see three options:
1. statically generated site
2. custom backend site + headless cms
3. Wordpress custom theme

## Statically Generated Site
With this option we you would need most of the content up front in markdown files then the site would build from that. This option would work great if the content on the site does not change that often. 

## Custom Backend
With this option the content would be stored in a cms so it can be edited. Then when the site is requested a custom backend (node.js + express) would receive the call and handle connecting to the cms to get the content and templating the html live and returning it to the browser. 

## Wordpress
Though I'm not a big fan of wordpress's php code I can't deny it does a great job of being a CMS + Server + Templating Backend. If we go this route I would advise a competently custom theme. No one will be able to tell its wordpress and the design will shine through. 

@MrTim  what do you think?

**Comment by BTBTravis** [comment]
There has be no interaction by student. Closing Issu

**Comment by anadanielkiewicz** [comment]
We discussed this topic in class. We came to the conclusion that it would be best to do CMS, but my project still needs a lot of work before I reach this stage. At the moment I focused on creating a page without the possibility of modifying it and on using js code.
